# Generated by Django 5.2.2 on 2025-06-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text="User's trading balance", max_digits=10),
        ),
    ]
