# Generated by Django 5.0.1 on 2025-06-13 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.CharField(help_text='The market premise or question', max_length=500)),
                ('unit_price', models.FloatField(help_text='Base unit price for trading')),
                ('spread_low', models.IntegerField(help_text='Lower bound of the spread')),
                ('spread_high', models.IntegerField(help_text='Upper bound of the spread')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SETTLED', 'Settled')], default='CREATED', help_text='Current status of the market', max_length=10)),
                ('spread_bidding_open', models.DateTimeField(help_text='When spread bidding opens')),
                ('spread_bidding_close', models.DateTimeField(help_text='When spread bidding closes')),
                ('trading_open', models.DateTimeField(help_text='When trading opens')),
                ('trading_close', models.DateTimeField(help_text='When trading closes')),
                ('outcome', models.IntegerField(blank=True, help_text='Final outcome of the market (set when settled)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this market', on_delete=django.db.models.deletion.CASCADE, related_name='created_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['-created_at'],
            },
        ),
    ]
