# Generated by Django 5.0.1 on 2025-06-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='spread_high',
        ),
        migrations.RemoveField(
            model_name='market',
            name='spread_low',
        ),
        migrations.AddField(
            model_name='market',
            name='final_spread_high',
            field=models.IntegerField(blank=True, help_text='Upper bound of the final spread (set through bidding)', null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='final_spread_low',
            field=models.IntegerField(blank=True, help_text='Lower bound of the final spread (set through bidding)', null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='initial_spread',
            field=models.IntegerField(default=3, help_text='Initial spread value set when creating the market'),
            preserve_default=False,
        ),
    ]
