# Generated by Django 5.0.1 on 2025-06-14 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_market_spread_high_remove_market_spread_low_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_low', models.IntegerField(help_text='Lower bound of the spread bid')),
                ('spread_high', models.IntegerField(help_text='Upper bound of the spread bid')),
                ('bid_time', models.DateTimeField(auto_now_add=True, help_text='When this bid was placed')),
                ('market', models.ForeignKey(help_text='The market this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='spread_bids', to='market.market')),
                ('user', models.ForeignKey(help_text='User placing the bid', on_delete=django.db.models.deletion.CASCADE, related_name='spread_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spread Bid',
                'verbose_name_plural': 'Spread Bids',
                'ordering': ['bid_time'],
                'indexes': [models.Index(fields=['market', 'bid_time'], name='market_spre_market__26e0ef_idx'), models.Index(fields=['user', 'market', 'bid_time'], name='market_spre_user_id_abbfe2_idx')],
            },
        ),
    ]
