# Generated by Django 5.0.1 on 2025-06-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trade',
            new_name='market_trad_market__bc5259_idx',
            old_name='market_trade_market__b8e8e8_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='market_trad_user_id_8d64de_idx',
            old_name='market_trade_user_id_b8e8e8_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='market_trad_market__3228a4_idx',
            old_name='market_trade_market__b8e8e9_idx',
        ),
    ]
