# Generated by Django 5.0.1 on 2025-06-21 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_final_outcome_market_market_maker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='spread_bidding_close',
        ),
        migrations.RemoveField(
            model_name='market',
            name='trading_open',
        ),
        migrations.AddField(
            model_name='market',
            name='spread_bidding_close_trading_open',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 0, 0), help_text='When spread bidding closes and trading opens'),
            preserve_default=False,
        ),
    ]
