# Generated by Django 5.0.1 on 2025-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_market_spread_bidding_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='settlement_confirmed',
            field=models.BooleanField(default=False, help_text='Whether admin has confirmed the settlement'),
        ),
        migrations.AddField(
            model_name='market',
            name='settlement_preview_calculated',
            field=models.BooleanField(default=False, help_text='Whether settlement preview has been calculated'),
        ),
        migrations.AlterField(
            model_name='market',
            name='settlement_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final settlement price (0.01 to 999999.99)', max_digits=12, null=True),
        ),
    ]
